//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int Cancellation_Id { get; set; }
        public int Pnr_no { get; set; }
        public int User_id { get; set; }
        public System.DateTime Dateofcancellation { get; set; }
        public System.TimeSpan timeofcancellation { get; set; }
        public int Refund_Amount { get; set; }
        public string Status { get; set; }
    
        public virtual Flight_Reservation Flight_Reservation { get; set; }
        public virtual User_Registration User_Registration { get; set; }
    }
}
