//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Information
    {
        public City_Information()
        {
            this.Flight_Schedules = new HashSet<Flight_Schedules>();
        }
    
        public int Airport_Code { get; set; }
        public string Airport_Name { get; set; }
        public string Location { get; set; }
        public int Zip_Code { get; set; }
    
        public virtual ICollection<Flight_Schedules> Flight_Schedules { get; set; }
    }
}
