//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Schedules
    {
        public Flight_Schedules()
        {
            this.Flight_Reservation = new HashSet<Flight_Reservation>();
        }
    
        public int Flight_Number { get; set; }
        public string Flight_Name { get; set; }
        public System.DateTime Flight_Date { get; set; }
        public int Airport_Code { get; set; }
        public System.TimeSpan Flight_Departing_Time { get; set; }
        public System.TimeSpan Flight_Arrival_Time { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Flight_Status { get; set; }
        public int Cost_Eco { get; set; }
        public int Cost_Business { get; set; }
        public Nullable<int> Seats_Available_Eco { get; set; }
        public Nullable<int> Seats_Available_Business { get; set; }
        public string Seats { get; set; }
    
        public virtual City_Information City_Information { get; set; }
        public virtual ICollection<Flight_Reservation> Flight_Reservation { get; set; }
    }
}
