//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Reservation
    {
        public Flight_Reservation()
        {
            this.Cancellations = new HashSet<Cancellation>();
            this.Passenger_Details = new HashSet<Passenger_Details>();
        }
    
        public int Pnr_no { get; set; }
        public int Flight_Number { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Reservation_Date { get; set; }
        public System.TimeSpan Reservation_Time { get; set; }
        public int num_of_Seats { get; set; }
        public string Classtype { get; set; }
        public Nullable<int> total_price { get; set; }
        public string status { get; set; }
        public string Seats { get; set; }
    
        public virtual ICollection<Cancellation> Cancellations { get; set; }
        public virtual Flight_Schedules Flight_Schedules { get; set; }
        public virtual User_Registration User_Registration { get; set; }
        public virtual ICollection<Passenger_Details> Passenger_Details { get; set; }
    }
}
