//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_AirlineReservation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AirlineDBEntities : DbContext
    {
        public AirlineDBEntities()
            : base("name=AirlineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cancellation> Cancellations { get; set; }
        public DbSet<City_Information> City_Information { get; set; }
        public DbSet<Flight_Reservation> Flight_Reservation { get; set; }
        public DbSet<Flight_Schedules> Flight_Schedules { get; set; }
        public DbSet<Passenger_Details> Passenger_Details { get; set; }
        public DbSet<Payment_Details> Payment_Details { get; set; }
        public DbSet<User_Registration> User_Registration { get; set; }
    
        public virtual ObjectResult<sp_BookedTickets_Result> sp_BookedTickets(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookedTickets_Result>("sp_BookedTickets", uidParameter);
        }
    
        public virtual ObjectResult<sp_BookingDetailsByID_Result> sp_BookingDetailsByID(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BookingDetailsByID_Result>("sp_BookingDetailsByID", uidParameter);
        }
    
        public virtual ObjectResult<sp_CancelledTickets_Result> sp_CancelledTickets(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CancelledTickets_Result>("sp_CancelledTickets", uidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_DateCompare(Nullable<int> flight_Number)
        {
            var flight_NumberParameter = flight_Number.HasValue ?
                new ObjectParameter("Flight_Number", flight_Number) :
                new ObjectParameter("Flight_Number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DateCompare", flight_NumberParameter);
        }
    
        public virtual ObjectResult<sp_GetAllFlightDetails_Result> sp_GetAllFlightDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllFlightDetails_Result>("sp_GetAllFlightDetails");
        }
    
        public virtual ObjectResult<sp_GetFlights_Result> sp_GetFlights(string flight_Name, string flight_Date, string origin, string destination)
        {
            var flight_NameParameter = flight_Name != null ?
                new ObjectParameter("Flight_Name", flight_Name) :
                new ObjectParameter("Flight_Name", typeof(string));
    
            var flight_DateParameter = flight_Date != null ?
                new ObjectParameter("Flight_Date", flight_Date) :
                new ObjectParameter("Flight_Date", typeof(string));
    
            var originParameter = origin != null ?
                new ObjectParameter("Origin", origin) :
                new ObjectParameter("Origin", typeof(string));
    
            var destinationParameter = destination != null ?
                new ObjectParameter("Destination", destination) :
                new ObjectParameter("Destination", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetFlights_Result>("sp_GetFlights", flight_NameParameter, flight_DateParameter, originParameter, destinationParameter);
        }
    
        public virtual ObjectResult<sp_GetIdByEmail_Result> sp_GetIdByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetIdByEmail_Result>("sp_GetIdByEmail", emailParameter);
        }
    
        public virtual ObjectResult<sp_GetPsgDetailsByPnr_Result> sp_GetPsgDetailsByPnr(Nullable<int> pnr)
        {
            var pnrParameter = pnr.HasValue ?
                new ObjectParameter("pnr", pnr) :
                new ObjectParameter("pnr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPsgDetailsByPnr_Result>("sp_GetPsgDetailsByPnr", pnrParameter);
        }
    
        public virtual ObjectResult<string> sp_GetSeatsByFlightNo(Nullable<int> flight_Number)
        {
            var flight_NumberParameter = flight_Number.HasValue ?
                new ObjectParameter("Flight_Number", flight_Number) :
                new ObjectParameter("Flight_Number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetSeatsByFlightNo", flight_NumberParameter);
        }
    
        public virtual int sp_InsertCardDetails(Nullable<int> userId, Nullable<long> cardNo, string cardtype, Nullable<int> expiry_Month, Nullable<int> expiry_year, Nullable<long> balance)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var cardNoParameter = cardNo.HasValue ?
                new ObjectParameter("CardNo", cardNo) :
                new ObjectParameter("CardNo", typeof(long));
    
            var cardtypeParameter = cardtype != null ?
                new ObjectParameter("cardtype", cardtype) :
                new ObjectParameter("cardtype", typeof(string));
    
            var expiry_MonthParameter = expiry_Month.HasValue ?
                new ObjectParameter("Expiry_Month", expiry_Month) :
                new ObjectParameter("Expiry_Month", typeof(int));
    
            var expiry_yearParameter = expiry_year.HasValue ?
                new ObjectParameter("Expiry_year", expiry_year) :
                new ObjectParameter("Expiry_year", typeof(int));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("Balance", balance) :
                new ObjectParameter("Balance", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertCardDetails", userIdParameter, cardNoParameter, cardtypeParameter, expiry_MonthParameter, expiry_yearParameter, balanceParameter);
        }
    
        public virtual int sp_UpdatePassword(string otp, string password)
        {
            var otpParameter = otp != null ?
                new ObjectParameter("otp", otp) :
                new ObjectParameter("otp", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdatePassword", otpParameter, passwordParameter);
        }
    
        public virtual int sp_UpdateSeats(Nullable<int> flight_Number, string seats)
        {
            var flight_NumberParameter = flight_Number.HasValue ?
                new ObjectParameter("Flight_Number", flight_Number) :
                new ObjectParameter("Flight_Number", typeof(int));
    
            var seatsParameter = seats != null ?
                new ObjectParameter("Seats", seats) :
                new ObjectParameter("Seats", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateSeats", flight_NumberParameter, seatsParameter);
        }
    }
}
