//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Details
    {
        public int User_Id { get; set; }
        public long CardNo { get; set; }
        public string cardtype { get; set; }
        public int Expiry_Month { get; set; }
        public int Expiry_year { get; set; }
        public int Balance { get; set; }
    
        public virtual User_Registration User_Registration { get; set; }
    }
}
