//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Registration
    {
        public User_Registration()
        {
            this.Cancellations = new HashSet<Cancellation>();
            this.Flight_Reservation = new HashSet<Flight_Reservation>();
            this.Payment_Details = new HashSet<Payment_Details>();
        }
    
        public int User_Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public System.DateTime DOB { get; set; }
        public long PhoneNumber { get; set; }
        public string OTP { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    
        public virtual ICollection<Cancellation> Cancellations { get; set; }
        public virtual ICollection<Flight_Reservation> Flight_Reservation { get; set; }
        public virtual ICollection<Payment_Details> Payment_Details { get; set; }
    }
}
